

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=credit_approval.settings

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  celery:
    build: .
    command: celery -A credit_approval worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - web
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=credit_approval.settings

  celery-beat:
    build: .
    command: celery -A credit_approval beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - web
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DJANGO_SETTINGS_MODULE=credit_approval.settings

volumes:
  postgres_data: